version: 2.1
orbs:
  microscanner: 'aquasecurity/microscanner@dev:0.1.1'
jobs:
  docker-build:
    executor: microscanner/default
    steps:
      - checkout
      - run: 'docker build -t suhimanju/docker-elk/logstash .'
workflows:
  scan-image:
    jobs:
      - docker-build
      - microscanner/scan-image:
          requires:
            - docker-build
          context: myContext
          image: 'suhimanju/docker-elk/logstash:docker-circleci'